-- MySQL Script generated by MySQL Workbench
-- Thu Jan 30 13:39:12 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema wine_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `wine_db` ;

-- -----------------------------------------------------
-- Schema wine_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wine_db` DEFAULT CHARACTER SET utf8 ;
USE `wine_db` ;

-- -----------------------------------------------------
-- Table `wine_db`.`appellation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wine_db`.`appellation` ;

CREATE TABLE IF NOT EXISTS `wine_db`.`appellation` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(254) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `appellation_name` (`name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 1412
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `wine_db`.`brand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wine_db`.`brand` ;

CREATE TABLE IF NOT EXISTS `wine_db`.`brand` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(500) NOT NULL,
  `address` VARCHAR(500) NULL DEFAULT NULL,
  `city` VARCHAR(100) NULL DEFAULT NULL,
  `location` VARCHAR(500) NULL DEFAULT NULL,
  `country` VARCHAR(100) NULL DEFAULT NULL,
  `phone` VARCHAR(100) NULL DEFAULT NULL,
  `fax` VARCHAR(100) NULL DEFAULT NULL,
  `web` VARCHAR(500) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `brand_name` (`name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 23109
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `wine_db`.`competition`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wine_db`.`competition` ;

CREATE TABLE IF NOT EXISTS `wine_db`.`competition` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `award` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `competition_award` (`award` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 642
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `wine_db`.`food`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wine_db`.`food` ;

CREATE TABLE IF NOT EXISTS `wine_db`.`food` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(300) NOT NULL,
  `type` VARCHAR(254) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `food_name` (`name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 239
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `wine_db`.`grape`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wine_db`.`grape` ;

CREATE TABLE IF NOT EXISTS `wine_db`.`grape` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(500) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `grape_name` (`name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 808
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `wine_db`.`web`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wine_db`.`web` ;

CREATE TABLE IF NOT EXISTS `wine_db`.`web` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `hash` VARCHAR(256) NOT NULL,
  `url` TINYTEXT NOT NULL,
  `modified` DATETIME NULL DEFAULT NULL,
  `type` ENUM('list', 'wine', 'user', 'review', 'brand', 'grape', 'appellation', 'location', 'pairing') NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `web_hash` (`hash` ASC),
  INDEX `web_modified` (`modified` ASC),
  INDEX `web_type` (`type` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 463957
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `wine_db`.`html`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wine_db`.`html` ;

CREATE TABLE IF NOT EXISTS `wine_db`.`html` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `web_id` INT(11) NOT NULL,
  `html` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_html_web` (`web_id` ASC),
  CONSTRAINT `fk_html_web`
    FOREIGN KEY (`web_id`)
    REFERENCES `wine_db`.`web` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 463850
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `wine_db`.`location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wine_db`.`location` ;

CREATE TABLE IF NOT EXISTS `wine_db`.`location` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(254) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `location_name` (`name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 131
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `wine_db`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wine_db`.`user` ;

CREATE TABLE IF NOT EXISTS `wine_db`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(254) NOT NULL COMMENT 'Username from the URL',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_username` (`username` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 3039
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `wine_db`.`review`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wine_db`.`review` ;

CREATE TABLE IF NOT EXISTS `wine_db`.`review` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `hash` VARCHAR(256) NOT NULL,
  `text` TEXT NOT NULL,
  `rating` FLOAT NULL DEFAULT NULL,
  `date` DATETIME NULL DEFAULT NULL,
  `source` VARCHAR(254) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `review_hash` (`hash` ASC),
  INDEX `fk_review_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_review_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `wine_db`.`user` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 136876
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `wine_db`.`wine`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wine_db`.`wine` ;

CREATE TABLE IF NOT EXISTS `wine_db`.`wine` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `brand_id` INT(11) NULL DEFAULT NULL,
  `appellation_id` INT(11) NULL DEFAULT NULL,
  `location_id` INT(11) NULL DEFAULT NULL,
  `hash` VARCHAR(256) NOT NULL COMMENT 'From the source URL',
  `name` VARCHAR(500) NOT NULL,
  `source` TINYTEXT NOT NULL,
  `dc_rating` FLOAT NULL DEFAULT '0' COMMENT 'Drinks&Co avg rating',
  `rp_rating` FLOAT NULL DEFAULT '0' COMMENT 'Parker rating',
  `ws_rating` FLOAT NULL DEFAULT '0' COMMENT 'Wine-searcher rating',
  `we_rating` FLOAT NULL DEFAULT '0' COMMENT 'Wine enthusiast rating',
  `external_id` VARCHAR(254) NULL DEFAULT NULL,
  `price` FLOAT NULL DEFAULT NULL COMMENT '$',
  `summary` TEXT NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `tasting_notes` TEXT NULL DEFAULT NULL,
  `type` VARCHAR(254) NULL DEFAULT NULL,
  `vintage` INT(11) NULL DEFAULT NULL,
  `volume` VARCHAR(50) NULL DEFAULT NULL COMMENT 'cl',
  `min_consumption_temp` INT(11) NULL DEFAULT NULL COMMENT 'ºC',
  `max_consumption_temp` INT(11) NULL DEFAULT NULL COMMENT 'ºC',
  `aging` VARCHAR(50) NULL DEFAULT NULL,
  `allergens` VARCHAR(254) NULL DEFAULT NULL,
  `alcohol_vol` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `wine_hash` (`hash` ASC),
  INDEX `fk_wine_brand1_idx` (`brand_id` ASC),
  INDEX `fk_wine_appellation1_idx` (`appellation_id` ASC),
  INDEX `fk_wine_location1_idx` (`location_id` ASC),
  CONSTRAINT `fk_wine_appellation1`
    FOREIGN KEY (`appellation_id`)
    REFERENCES `wine_db`.`appellation` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_wine_brand1`
    FOREIGN KEY (`brand_id`)
    REFERENCES `wine_db`.`brand` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_wine_location1`
    FOREIGN KEY (`location_id`)
    REFERENCES `wine_db`.`location` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 9856
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `wine_db`.`wine_competition`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wine_db`.`wine_competition` ;

CREATE TABLE IF NOT EXISTS `wine_db`.`wine_competition` (
  `wine_id` INT(11) NOT NULL,
  `competition_id` INT(11) NOT NULL,
  PRIMARY KEY (`wine_id`, `competition_id`),
  INDEX `fk_wine_competition_competition1_idx` (`competition_id` ASC),
  INDEX `fk_wine_competition_wine1_idx` (`wine_id` ASC),
  CONSTRAINT `fk_wine_competition_competition1`
    FOREIGN KEY (`competition_id`)
    REFERENCES `wine_db`.`competition` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_wine_competition_wine1`
    FOREIGN KEY (`wine_id`)
    REFERENCES `wine_db`.`wine` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `wine_db`.`wine_food`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wine_db`.`wine_food` ;

CREATE TABLE IF NOT EXISTS `wine_db`.`wine_food` (
  `wine_id` INT(11) NOT NULL,
  `food_id` INT(11) NOT NULL,
  PRIMARY KEY (`wine_id`, `food_id`),
  INDEX `fk_wine_food_food1_idx` (`food_id` ASC),
  INDEX `fk_wine_food_wine1_idx` (`wine_id` ASC),
  CONSTRAINT `fk_wine_food_food1`
    FOREIGN KEY (`food_id`)
    REFERENCES `wine_db`.`food` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_wine_food_wine1`
    FOREIGN KEY (`wine_id`)
    REFERENCES `wine_db`.`wine` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `wine_db`.`wine_grape`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wine_db`.`wine_grape` ;

CREATE TABLE IF NOT EXISTS `wine_db`.`wine_grape` (
  `wine_id` INT(11) NOT NULL,
  `grape_id` INT(11) NOT NULL,
  PRIMARY KEY (`wine_id`, `grape_id`),
  INDEX `fk_wine_grape_grape1_idx` (`grape_id` ASC),
  INDEX `fk_wine_grape_wine1_idx` (`wine_id` ASC),
  CONSTRAINT `fk_wine_grape_grape1`
    FOREIGN KEY (`grape_id`)
    REFERENCES `wine_db`.`grape` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_wine_grape_wine1`
    FOREIGN KEY (`wine_id`)
    REFERENCES `wine_db`.`wine` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `wine_db`.`wine_review`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wine_db`.`wine_review` ;

CREATE TABLE IF NOT EXISTS `wine_db`.`wine_review` (
  `wine_id` INT(11) NOT NULL,
  `review_id` INT(11) NOT NULL,
  PRIMARY KEY (`wine_id`, `review_id`),
  INDEX `fk_wine_review_review1_idx` (`review_id` ASC),
  INDEX `fk_wine_review_wine1_idx` (`wine_id` ASC),
  CONSTRAINT `fk_wine_review_review1`
    FOREIGN KEY (`review_id`)
    REFERENCES `wine_db`.`review` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_wine_review_wine1`
    FOREIGN KEY (`wine_id`)
    REFERENCES `wine_db`.`wine` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
